### ISSUE TITLE
Hand Calc non-functional?

### ISSUE THREAD

**Issue by AlphaKretin** [Solumin/YGO-DotR-FusionCalc#1]
This is a really stupid question, but is there something you have to do to make the hand fusion calculator 'go'? It doesn't seem to work for me, when I've confirmed with the fusion search that a fusion exists in my hand. (Corroding Shark + Winged Dragon Guardian of the Fortress #1 = Dragon Zombie, for reference, filled in with autocomplete.)

**Comment by Solumin** [comment]
That combination works fine for me:
![fusion](https://cloud.githubusercontent.com/assets/930857/17270869/1c58cff6-563b-11e6-843d-e3d27355d21d.PNG)

What browser are you using? The hand calculator uses some JavaScript 6 features, and your browser might not support that.

**Comment by AlphaKretin** [comment]
Firefox, both Windows and Android. I'll give chrome a shot in the morning (Australian time).

**Comment by AlphaKretin** [comment]
Actually just tried Android Chrome and whaddya know. Wish I thought of that before I beat the game but maybe checking being more tedious is what inspired me to experiment as much as I did. :V Guess it must be a Firefox thing.

**Comment by Solumin** [comment]
I haven't done any testing on Firefox at all (or on any browsers besides non-mobile Chrome) so that's partially my fault.

It's ugly but it works:
![firefox](https://cloud.githubusercontent.com/assets/930857/17270958/cf82d0da-563c-11e6-8a49-ac670943562f.PNG)
This is with Firefox 47.0.1. Are you using an older version maybe?

**Comment by AlphaKretin** [comment]
Ah, probably. I'm pretty slack about letting things update, ahaha. Thanks anyway.
