### ISSUE TITLE
I found a data-mined list of Fusions

### ISSUE THREAD

**Issue by AlphaKretin** [Solumin/YGO-DotR-FusionCalc#8]
https://docs.google.com/spreadsheets/d/1N1Q5uf3Xbf1KyWx0iI3REoQi7NrqdwSHb0oR06UH-LE/edit?usp=sharing

It's by ID, so it would take a little programmatic legwork to convert it to a fusions.csv. I'm trying myself, but if you're still watching this and get to it before me or I burn out or anything, there ya go. 

For posterity's sake, I got this (and there's a bunch of other stuff) here:
https://www.speedrun.com/Yu-Gi-Oh_The_Duelists_of_the_Roses/thread/ch2hb

**Comment by AlphaKretin** [comment]
I got it done, I'll make a pull request as soon as my GitHub client stops choking on the size...

**Comment by Solumin** [comment]
Thank you so much! Merged.
